version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    volumes: 
      - ./host-db/redis-data:/data/redis:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_LOGGING=$DB_LOGGING
      - DB_SYNC=$DB_SYNC
      - DB_HOST=mysqldb
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - NODE_PORT=$NODE_DOCKER_PORT
      - NODE_PASSWORD_SECRET=$NODE_PASSWORD_SECRET
      - NODE_PASSWORD_SALT=$NODE_PASSWORD_SALT
      - NODE_JWT_SECRET=$NODE_JWT_SECRET
      - NODE_JWT_EXPIRES=$NODE_JWT_EXPIRES
      - REDIS_HOST=$REDIS_DOCKER_HOST
      - REDIS_PORT=$REDIS_DOCKER_PORT
    volumes:
      - ./:/api-test
    stdin_open: true
    tty: true
volumes: 
  db: